config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'next_image', to: 'api/api#next_image'
    get 'prev_image', to: 'api/api#prev_image'
  end
  get 'work/index'
  get 'work/choose_theme'
  get 'work/display_theme'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  post   'signin',  to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
  resources :themes
  resources :sessions,only: [:new,:create,:destroy]
  resources :images
  resources :values
  resources :users
  #work
  get 'work', to: 'work#index'
  get 'choose_theme', to: 'work#choose_theme'
  post 'display_theme', to: 'work#display_theme'

  #root'work#index'
  get 'main/index'
  get 'contacts', to: 'main#contacts', as: 'main_contacts'
  get 'help', to: 'main#help', as: 'main_help'
  get 'about', to: 'main#about', as: 'main_about'
  root 'main#index'
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :images
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: %i[ show edit update destroy ]

  # GET /themes or /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1 or /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes or /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: "Theme was successfully created." }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1 or /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: "Theme was successfully updated." }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1 or /themes/1.json
  def destroy
    @theme.destroy!

    respond_to do |format|
      format.html { redirect_to themes_path, status: :see_other, notice: "Theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:name, :qty_items)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.slim
= form_with(model: theme) do |form|
  - if theme.errors.any?
    div style="color: red"
      h2 = "#{pluralize(theme.errors.count, "error")} prohibited this theme from being saved:"
      ul
        - theme.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :qty_items, style: "display: block"
    = form.number_field :qty_items

  div
    = form.submit

app/views/themes/_theme.html.slim
div id="#{dom_id theme}"
  p
    strong Name:
    =< theme.name
  p
    strong Qty items:
    =< theme.qty_items

app/views/themes/edit.html.slim
h1 Editing theme

== render "form", theme: @theme

br

div
  => link_to "Show this theme", @theme
  '|
  =< link_to "Back to themes", themes_path

app/views/themes/index.html.slim
p style="color: green" = notice

h1 Themes

#themes
  - @themes.each do |theme|
    == render theme
    p
      = link_to "Show this theme", theme

= link_to "New theme", new_theme_path

app/views/themes/new.html.slim
h1 New theme

== render "form", theme: @theme

br

div
  = link_to "Back to themes", themes_path

app/views/themes/show.html.slim
p style="color: green" = notice

== render @theme

div
  => link_to "Edit this theme", edit_theme_path(@theme)
  '|
  =< link_to "Back to themes", themes_path

  = button_to "Destroy this theme", @theme, method: :delete