config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'next_image', to: 'api/api#next_image'
    get 'prev_image', to: 'api/api#prev_image'
  end
  get 'work/index'
  get 'work/choose_theme'
  get 'work/display_theme'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  post   'signin',  to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
  resources :themes
  resources :sessions,only: [:new,:create,:destroy]
  resources :images
  resources :values
  resources :users
  #work
  get 'work', to: 'work#index'
  get 'choose_theme', to: 'work#choose_theme'
  post 'display_theme', to: 'work#display_theme'

  #root'work#index'
  get 'main/index'
  get 'contacts', to: 'main#contacts', as: 'main_contacts'
  get 'help', to: 'main#help', as: 'main_help'
  get 'about', to: 'main#about', as: 'main_about'
  root 'main#index'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :email, presence: true,
            format: { with: URI::MailTo::EMAIL_REGEXP},
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
  has_many :values, dependent: :destroy
  # todo: validations
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email,:password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label t('.name')
    = f.text_field :name

  .field
    = f.label t('.email')
    = f.text_field :email

  .field
    = f.label t('.password')
    = f.password_field :password

  .field
    = f.label t('.password_confirmation')
    = f.password_field :password_confirmation

  .actions
    / = f.submit 'Save'
    = f.submit t(".create_account"), class: "btn btn-large btn-primary"

app/views/users/_user.html.slim
div id="#{dom_id user}"
  p
    strong Name:
    =< user.name
  p
    strong Email:
    =< user.email

app/views/users/edit.html.slim
h1 Editing user

== render "form", user: @user

br

div
  => link_to "Show this user", @user
  '|
  =< link_to "Back to users", users_path

app/views/users/index.html.slim
p style="color: green" = notice

h1 Users

#users
  - @users.each do |user|
    == render user
    p
      = link_to "Show this user", user

= link_to "New user", new_user_path

app/views/users/new.html.slim
h1 New user

== render "form", user: @user
br


div
  = link_to "Back to users", users_path

app/views/users/show.html.slim
.show_user
  p style="color: green" = notice
  == render @user
  = link_to t('.work'), work_path, class: "btn btn-lg btn-primary"

  div
    | &nbsp;
    = link_to "Edit this user", edit_user_path(@user)
    |  | 
    = link_to "Back to users", users_path

  section.user_info
    = gravatar_for @user
    h1= @user.name
    p= @user.email
    = button_to "Destroy this user", @user, method: :delete