config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'next_image', to: 'api/api#next_image'
    get 'prev_image', to: 'api/api#prev_image'
  end
  get 'work/index'
  get 'work/choose_theme'
  get 'work/display_theme'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  post   'signin',  to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
  resources :themes
  resources :sessions,only: [:new,:create,:destroy]
  resources :images
  resources :values
  resources :users
  #work
  get 'work', to: 'work#index'
  get 'choose_theme', to: 'work#choose_theme'
  post 'display_theme', to: 'work#display_theme'

  #root'work#index'
  get 'main/index'
  get 'contacts', to: 'main#contacts', as: 'main_contacts'
  get 'help', to: 'main#help', as: 'main_help'
  get 'about', to: 'main#about', as: 'main_about'
  root 'main#index'
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :theme
  scope :theme_images, ->(theme_id) {
    select(:id, :name, :file, :ave_value).where(theme_id: theme_id)
  }
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
    @image = Image.find(params[:id])
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy!

    respond_to do |format|
      format.html { redirect_to images_path, status: :see_other, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name, :file, :ave_value, :theme_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.slim
= form_with(model: image) do |form|
  - if image.errors.any?
    div style="color: red"
      h2 = "#{pluralize(image.errors.count, "error")} prohibited this image from being saved:"
      ul
        - image.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :file, style: "display: block"
    = form.text_field :file

  div
    = form.label :theme_id, style: "display: block"
    = form.number_field :theme_id

  div
    = form.submit

app/views/images/_image.html.slim
div(id="#{dom_id image}")
  p
    strong Name:
    =< image.name
  p
    strong File:
    =< image.file
  p
    strong Ave value:
    =< image.ave_value
  p
    strong Theme:
    =< image.theme_id

  - if controller.controller_name == 'images' && controller.action_name == 'show'
    .rating-slider.mb-3
      = form_with(model: image, class: "ave-rating-form") do |f|
        .d-flex.align-items-center.gap-3
          = f.label :ave_value, "Value (0-10):", class: "form-label mb-0"
          = f.range_field :ave_value,
                  in: 0..10,
                  step: 1,
                  class: "form-range slider-input",
                  data: { target: "aveValue.output" }
          span.slider-value.badge.bg-primary.fs-6.ms-2[data-slider-target="value"]
            = image.ave_value || 0
          = f.submit "Save", class: "btn btn-sm btn-primary ms-3"

app/views/images/edit.html.slim
h1 Editing image

== render "form", image: @image

br

div
  => link_to "Show this image", @image
  '|
  =< link_to "Back to images", images_path

app/views/images/index.html.slim
p style="color: green" = notice

h1 Images

#images
  - @images.each do |image|
    == render image
    p
      = link_to "Show this image", image

= link_to "New image", new_image_path

app/views/images/new.html.slim
h1 New image

== render "form", image: @image

br

div
  = link_to "Back to images", images_path

app/views/images/show.html.slim
p style="color: green" = notice

== render @image

div
  = image_tag "pictures/#{@image.file}"
  => link_to "Edit this image", edit_image_path(@image)
  '|
  =< link_to "Back to images", images_path


  = button_to "Destroy this image", @image, method: :delete